In [ ]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
import math
from tensorflow import keras

#tf version should be 2.5 or higher
tf.__version__

'2.6.0'

'2.6.0'

In [ ]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [ ]:
#scale model
# train_images = train_images / 255.0
# test_images = test_images / 255.0

# reshape inputs for CNN layers
train_images = train_images.reshape(train_images.shape[0], 28, 28, 1)
test_images = test_images.reshape(test_images.shape[0], 28, 28, 1)
train_images = train_images / 255.0
test_images = test_images / 255.0
 

In [ ]:
#setup model
# model = keras.Sequential([
#     keras.layers.Flatten(input_shape=(28, 28)),
#     keras.layers.Dense(200, activation = 'relu'),
#     keras.layers.Dropout(0.25),
#     keras.layers.Dense(100, activation = 'relu'),
#     keras.layers.Dropout(0.25),
#     keras.layers.Dense(60, activation = 'relu'),
#     keras.layers.Dropout(0.25),
#     keras.layers.Dense(10, activation = tf.nn.softmax)
# ])

#setup CNN model
model = keras.Sequential([
      # tf.keras.layers.Reshape(input_shape=(28*28,), target_shape(28,28,1)),

      keras.layers.Conv2D(kernel_size = 3, filters = 12, activation = 'relu', padding = 'same', input_shape=(28,28,1)), 
      tf.keras.layers.BatchNormalization(center = True, scale = False),
      tf.keras.layers.Activation('relu'),

      keras.layers.Conv2D(kernel_size = 6, filters = 24, activation = 'relu', padding = 'same', strides = 2),
      tf.keras.layers.BatchNormalization(center = True, scale = False),
      tf.keras.layers.Activation('relu'),

      keras.layers.Conv2D(kernel_size = 6, filters = 32, activation = 'relu', padding = 'same', strides = 2),
      tf.keras.layers.BatchNormalization(center = True, scale = False),
      tf.keras.layers.Activation('relu'),

      keras.layers.Flatten(),

      keras.layers.Dense(200, use_bias = False),
      tf.keras.layers.BatchNormalization(center = True, scale = False),
      tf.keras.layers.Activation('relu'),
      keras.layers.Dropout(0.25),

      keras.layers.Dense(100, activation = 'relu'),
       tf.keras.layers.BatchNormalization(center = True, scale = False),
      tf.keras.layers.Activation('relu'),
      keras.layers.Dropout(0.25),

      keras.layers.Dense(10, activation = 'softmax')
      ])

In [ ]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [ ]:
#lr decay function
def lr_decay(epoch):
  return 0.01 * math.pow(0.6, epoch)

#lr schedule callback
lr_decay_callback = tf.keras.callbacks.LearningRateScheduler(lr_decay,)

In [ ]:
#train model
model.fit(train_images, train_labels, epochs=10, callbacks = [lr_decay_callback])

Epoch 1/10
1875/1875 [==============================] - 111s 59ms/step - loss: 0.1839 - accuracy: 0.9476
Epoch 2/10
1875/1875 [==============================] - 110s 59ms/step - loss: 0.0732 - accuracy: 0.9797
Epoch 3/10
1875/1875 [==============================] - 110s 59ms/step - loss: 0.0474 - accuracy: 0.9862
Epoch 4/10
1875/1875 [==============================] - 111s 59ms/step - loss: 0.0279 - accuracy: 0.9915
Epoch 5/10
1875/1875 [==============================] - 109s 58ms/step - loss: 0.0220 - accuracy: 0.9935
Epoch 6/10
1875/1875 [==============================] - 110s 59ms/step - loss: 0.0142 - accuracy: 0.9956
Epoch 7/10
1875/1875 [==============================] - 110s 58ms/step - loss: 0.0119 - accuracy: 0.9966
Epoch 8/10
1875/1875 [==============================] - 109s 58ms/step - loss: 0.0099 - accuracy: 0.9969
Epoch 9/10
1875/1875 [==============================] - 108s 58ms/step - loss: 0.0075 - accuracy: 0.9977
Epoch 10/10
1875/1875 [==============================] 

In [ ]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 5s 16ms/step - loss: 0.0182 - accuracy: 0.9953

Test accuracy: 0.9952999949455261


In [ ]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

In [ ]:
#Raw predictions
predictions

array([[4.57859410e-11, 4.17016992e-07, 1.80890950e-07, 2.12831743e-08,
        1.18233876e-08, 4.05363493e-10, 1.13033971e-10, 9.99999046e-01,
        4.08824197e-10, 2.34832612e-07],
       [3.20075112e-11, 1.61292313e-08, 1.00000000e+00, 2.98253913e-12,
        2.33115000e-10, 1.21662204e-17, 1.47526773e-08, 1.71025294e-09,
        5.78895872e-12, 3.69578473e-13],
       [1.90523026e-13, 1.00000000e+00, 5.97817640e-13, 2.63105215e-16,
        2.35136910e-11, 1.61029772e-12, 1.37702585e-10, 1.02093889e-09,
        2.69087877e-12, 2.73872667e-13],
       [9.99999404e-01, 1.70532366e-09, 4.20613055e-09, 2.88911655e-11,
        1.13602669e-10, 8.04594655e-11, 6.05657988e-07, 4.35939391e-08,
        5.60830982e-09, 1.74766990e-09],
       [8.18839496e-10, 1.97042649e-08, 3.59094421e-10, 2.22956270e-13,
        9.99997020e-01, 1.15384835e-09, 5.29443644e-09, 4.98574662e-12,
        6.01531269e-08, 2.96310191e-06]], dtype=float32)

In [ ]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [ ]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
